apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "kubeat.fullname" . }}
  labels:
    app: {{ template "kubeat.name" . }}
    chart: {{ template "kubeat.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubeat_disable: "{{ .Values.disable_self_logging }}"
spec:
  replicas: 1
  maxReplicas: 1
  selector:
    matchLabels:
      app: {{ template "kubeat.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "kubeat.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      automountServiceAccountToken: true
      volumes:
        - name: {{ template "kubeat.fullname" . }}-config
          configMap:
            name: {{ template "kubeat.fullname" . }}-config
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: {{ toJson .Values.image.args }}
          {{- if .Values.secret.create }}
          env:
            - name: KUBEAT_ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ template "kubeat.fullname" . }}-elastic
                  key: username
            - name: KUBEAT_ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ template "kubeat.fullname" . }}-elastic
                  key: password
          {{- end }}
          volumeMounts:
            - name: {{ template "kubeat.fullname" . }}-config
              mountPath: /data
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
