apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "kubeat.name" . }}
    chart: {{ template "kubeat.chart" . }}
    release: {{ .Release.Name }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
  name: {{ template "kubeat.fullname" . }}-config
data:
  kubeat.json: |
{{ toJson .Values.configmap | indent 4 }}
